# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5] #, 3.6, 3.7, 3.8, 3.9]
        ansible-version: [2.9.18] #, 2.10.7]

    steps:
    - uses: actions/checkout@v2

    - name: Debug host github actions
      run: |
        sudo systemctl status ssh
        sudo apt update
        sudo apt install -y net-tools
        sudo netstat -anp
        sudo ls /etc/ssh/
        sudo cat /etc/ssh/sshd_config


    - name: OS, users and ssh requirements
      run: |
        id
        exit 1
        sudo apt update
        sudo DEBIAN_FRONTEND=noninteractive apt install -y openssh-server openssh-client
        echo -e 'passwordsuper\npasswordsuper' | sudo adduser chaos --shell /bin/bash
        echo -e 'passwordsuper\npasswordsuper' | sudo adduser chaossudopasswd --shell /bin/bash
        sudo ssh-keygen -A
        sudo sudo -u chaos ssh-keygen -q -N "" -f /home/chaos/.ssh/id_rsa
        sudo sudo -u chaos cp /home/chaos/.ssh/id_rsa.pub /home/chaos/.ssh/authorized_keys
        sudo sudo -u chaossudopasswd mkdir /home/chaossudopasswd/.ssh
        sudo cp /home/chaos/.ssh/id_rsa.pub /home/chaossudopasswd/.ssh/authorized_keys
        sudo chown -R chaossudopasswd: /home/chaossudopasswd/.ssh/authorized_keys
        sudo chmod 400 /home/chaossudopasswd/.ssh/authorized_keys
        sudo sh -c 'echo "chaos ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/chaos'
        sudo sh -c 'echo "chaossudopasswd ALL=(ALL) ALL" > /etc/sudoers.d/chaossudopasswd'
        sudo sh -c 'echo "\nPubkeyAuthentication yes\n\nAuthorizedKeysFile	.ssh/authorized_keys\n" >> /etc/ssh/sshd_config'
        sudo sh -c 'echo "\n   StrictHostKeyChecking no\n" >> /etc/ssh/ssh_config'
        sudo cat /etc/ssh/ssh_config
        sudo systemctl restart ssh

    - name: Debug host github actions 2
      run: |
        sudo -u chaos ssh 127.0.0.1 "ls -la"
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Set up ansible ${{ matrix.ansible-version}}
      run: python -m pip install ansible==${{ matrix.ansible-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pylama
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with pylama
      run: |
        pylama --ignore C901  chaosansible/
        
    - name: Test with pytest
      run: |
        pytest .

    - name: Run chaos with ansible test
      run: |
        sudo -u chaos chaos run chaos-integration-tests/withoutbecomepasswd.json

    

        

  