name: Release

on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  release-to-pypi:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel twine bumpversion

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        python3 setup.py release
        twine upload dist/*

    # push artifacts for other jobs to use
    - name: Upload packages as artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: chaostoolkit-ansible
        path: dist/chaostoolkit-*